### ISSUE TITLE
v2.2 版本使用windows_x64_admin.exe报错runtime error

### ISSUE THREAD

**Issue by sanmdfg** [ph4ntonn/Stowaway#61]
$ .\windows_x64_admin.exe -l 9999
```
[*] Starting admin node on port 9999

    .-')    .-') _                  ('\ .-') /'  ('-.      ('\ .-') /'  ('-.
   ( OO ). (  OO) )                  '.( OO ),' ( OO ).-.   '.( OO ),' ( OO ).-.
   (_)---\_)/     '._  .-'),-----. ,--./  .--.   / . --. /,--./  .--.   / . --. /  ,--.   ,--.
   /    _ | |'--...__)( OO'  .-.  '|      |  |   | \-.  \ |      |  |   | \-.  \    \  '.'  /
   \  :' '. '--.  .--'/   |  | |  ||  |   |  |,.-'-'  |  ||  |   |  |,.-'-'  |  | .-')     /
    '..'''.)   |  |   \_) |  |\|  ||  |.'.|  |_)\| |_.'  ||  |.'.|  |_)\| |_.'  |(OO  \   /
   .-._)   \   |  |     \ |  | |  ||         |   |  .-.  ||         |   |  .-.  | |   /  /\_
   \       /   |  |      ''  '-'  '|   ,'.   |   |  | |  ||   ,'.   |   |  | |  | '-./  /.__)
    '-----'    '--'        '-----' '--'   '--'   '--' '--''--'   '--'   '--' '--'   '--'
                                    { v2.2  Author:ph4ntom }
[*] Waiting for new connection...
[*] Connection from node 10.10.1.220:56798 is set up successfully! Node id is 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x99 pc=0xf56c52]

goroutine 1 [running]:
Stowaway/admin/process.(*Admin).Run(0xc00008a288)
        Stowaway/admin/process/process_win.go:50 +0x632
main.main()
        ./admin_win.go:68 +0x6e8
```

**Comment by ph4ntonn** [comment]
agent是如何启动的？

**Comment by ph4ntonn** [comment]
漏改win的对应代码，已修复
